service: documentation-example
app:  documentation-example
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2


custom: 
  autoswagger: 
    typefiles: ['./src/models/documentation-model.d.ts']

functions: ${file(serverless-files/serverless-functions-definitions.yml)}

plugins: 
  - serverless-auto-swagger
  - serverless-offline
  - serverless-webpack