// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "documentation-example",
    "version": "1"
  },
  "paths": {
    "/documentation/": {
      "post": {
        "summary": "postDocumentationExample",
        "description": "",
        "operationId": "postDocumentationExample.post.documentation/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Document"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "getDocumentationExample",
        "description": "",
        "operationId": "getDocumentationExample.get.documentation/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Document": {
      "properties": {
        "id": {
          "title": "Document.id",
          "type": "string"
        },
        "name": {
          "title": "Document.name",
          "type": "string"
        }
      },
      "required": [
        "id",
        "name"
      ],
      "additionalProperties": false,
      "title": "Document",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};